services:
# App
  GoRecord:
    container_name: Go-Record-WebUI
    image:  docker.io/lunanightbyte/gorecord:v0.0.1
    build:
      context: .
      dockerfile: docker/Dockerfile.run 
    ports:
      - "8050:80"
    volumes:
      - ./.env:/app/.env
      - ./internal/settings:/app/internal/settings
    tty: true
    privileged: true

# BUILD
# Core dependencies
  base: 
    image:  docker.io/lunanightbyte/gorecord-base:v0.0.1
    build:
      context: .
      dockerfile: docker/Dockerfile.base 

