x-defaults: &default-opts
  tty: true
  privileged: true
  ports:
    - "8050:80"
  volumes:
    - ./internal/app/db:/app/internal/db
    - ./output:/app/output #Safest to alway have output files in this folder.
services:

# App
  GoRecord:
    <<: *default-opts
    container_name: Go-Record-WebUI
    image:  docker.io/lunanightbyte/gorecord:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.run 


# BUILD
# Core dependencies
  dev: 
    <<: *default-opts
    image:  docker.io/lunanightbyte/gorecord-base:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.base 

    volumes:
      - ./:/app # We use the entire workdir for development.
    tty: true
    privileged: true
