services:
# App
  GoRecord:
    container_name: Go-Record-WebUI
    image:  docker.io/lunanightbyte/gorecord:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.run 
    ports:
      - "8050:80"
    volumes:
      - ./.env:/app/.env
      - ./internal/settings:/app/internal/settings
      - ./output:/app/output #Safest to alway have output files in this folder.
    tty: true
    privileged: true

# BUILD
# Vue dependencies
  vue: 
    image:  docker.io/lunanightbyte/gorecord-extra:v0.0.1
    build:
      context: .
      dockerfile: docker/Dockerfile.extra 
# Core dependencies
  base: 
    image:  docker.io/lunanightbyte/gorecord-base:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.base 

