name: Go Record Webui

on:
  release:
    types: [published]

jobs:
  build-and-push:
    environment: "Docker Build Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          fetch-tags: true 
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build Base
        run: |
          docker build -f docker/Dockerfile.base --build-arg VERSION=${{ env.VERSION }} -t lunanightbyte/gorecord-base:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord-base:${{ env.VERSION }} lunanightbyte/gorecord-base:latest
      - name: Push Base image
        run: |
          docker push lunanightbyte/gorecord-base:${{ env.VERSION }}
          docker push lunanightbyte/gorecord-base:latest

      - name: Build Minimal
        run: |
          docker build -f docker/Dockerfile.run -t lunanightbyte/gorecord:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord:${{ env.VERSION }} lunanightbyte/gorecord:latest
          
      - name: Push Minimal image
        run: |
          docker push lunanightbyte/gorecord:${{ env.VERSION }}
          docker push lunanightbyte/gorecord:latest
