name: Go Record Webui

on:
  release:
    types: [published]
  # Uncomment the following if you also want the workflow to run on branch pushes.
  # push:
  #   branches:
  #     - '**'

jobs:
  build-and-push:
    environment: "Docker Build Release"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          fetch-tags: true 

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract branch name
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build Base
        run: |
          VERSION_TAG="${{ env.VERSION }}"
          if [ -n "${{ env.BRANCH_NAME }}" ]; then
            VERSION_TAG="${{ env.VERSION }}-${{ env.BRANCH_NAME }}"
          fi
          echo "Using VERSION_TAG: ${VERSION_TAG}"
          docker build -f docker/Dockerfile.base --build-arg VERSION=${VERSION_TAG} -t lunanightbyte/gorecord-base:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord-base:${{ env.VERSION }} lunanightbyte/gorecord-base:latest

      - name: Push Base image
        run: |
          docker push lunanightbyte/gorecord-base:${{ env.VERSION }}
          docker push lunanightbyte/gorecord-base:latest

      - name: Build Minimal
        run: |
          docker build -f docker/Dockerfile.run -t lunanightbyte/gorecord:${{ env.VERSION }} .
          docker tag lunanightbyte/gorecord:${{ env.VERSION }} lunanightbyte/gorecord:latest

      - name: Push Minimal image
        run: |
          docker push lunanightbyte/gorecord:${{ env.VERSION }}
          docker push lunanightbyte/gorecord:latest
